const menu=document.querySelector('.menu'),nav=document.querySelector('#navigation');
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Menü schließen':'Menü öffnen');nav.classList.toggle('open',open)});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Menü öffnen')}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav?.classList.contains('open')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Menü öffnen');menu.focus()}});
const box=document.querySelector('#lightbox');document.querySelectorAll('.zoom-image').forEach(b=>b.addEventListener('click',()=>{box.querySelector('img').src=b.dataset.image;box.querySelector('img').alt=b.querySelector('img').alt;box.showModal()}));document.querySelector('.close-lightbox')?.addEventListener('click',()=>box.close());box?.addEventListener('click',e=>{if(e.target===box)box.close()});
document.querySelector('#project-form')?.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;const status=form.querySelector('#form-status');const button=form.querySelector('button[type=submit]');const data=new FormData(form);const selected=form.querySelector('select[name=service]').selectedOptions[0].textContent;data.set('_subject','Neue Projektanfrage: '+selected);button.disabled=true;status.textContent='Ihre Anfrage wird gesendet …';try{const response=await fetch(form.action,{method:'POST',headers:{Accept:'application/json'},body:data});if(!response.ok)throw new Error('send-failed');status.textContent='Vielen Dank! Ihre Anfrage ist bei uns angekommen. Wir melden uns so schnell wie möglich.';form.reset()}catch(err){status.textContent='Die Anfrage konnte nicht automatisch gesendet werden. Bitte schreiben Sie uns direkt an info@melmaler.de oder rufen Sie an: 0176 581 357 74.'}finally{button.disabled=false}});
const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();
const ldJson=document.createElement('script');ldJson.type='application/ld+json';ldJson.textContent=JSON.stringify({"@context":"https://schema.org","@type":"GeneralContractor","name":"Mel Maler","image":"https://www.melmaler.de/assets/mel-kompakt.jpeg","url":"https://www.melmaler.de/","telephone":"+4917658135774","email":"info@melmaler.de","address":{"@type":"PostalAddress","streetAddress":"Kennedystraße 4","postalCode":"82178","addressLocality":"Puchheim","addressCountry":"DE"},"areaServed":"Puchheim und Umgebung","sameAs":["https://www.instagram.com/melmalerbetrieb/"]});document.head.appendChild(ldJson);
const serviceSelect=document.querySelector('select[name=service]');const requestedService=new URLSearchParams(window.location.search).get('leistung');if(serviceSelect&&[...serviceSelect.options].some(o=>o.value===requestedService))serviceSelect.value=requestedService;

// Decorative motion never hides content or prevents navigation.
const motionPreference=window.matchMedia('(prefers-reduced-motion: reduce)');
if(!motionPreference.matches&&'IntersectionObserver' in window){
 const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-revealed');observer.unobserve(entry.target)}})},{threshold:.12});
 document.querySelectorAll('.section-head,.service,.detail-grid article,.process-grid article,.living-copy,.material-demo,.about-copy,.page-cta>div').forEach((el,i)=>{el.classList.add('reveal-once');el.style.setProperty('--reveal-delay',`${Math.min(i%4,3)*65}ms`);observer.observe(el)});
 motionPreference.addEventListener('change',event=>{if(event.matches)observer.disconnect()});
}
const progress=document.createElement('div');progress.className='scroll-progress';progress.setAttribute('aria-hidden','true');document.body.append(progress);let scrollScheduled=false;
function updateProgress(){const distance=document.documentElement.scrollHeight-window.innerHeight;progress.style.transform=`scaleX(${distance>0?Math.min(1,Math.max(0,window.scrollY/distance)):0})`;scrollScheduled=false}
window.addEventListener('scroll',()=>{if(!scrollScheduled){scrollScheduled=true;requestAnimationFrame(updateProgress)}},{passive:true});window.addEventListener('resize',updateProgress);updateProgress();
document.querySelectorAll('.material-demo').forEach(demo=>{demo.querySelectorAll('.palette-choice').forEach(button=>{button.addEventListener('click',()=>{demo.style.setProperty('--sample',button.dataset.color);demo.querySelectorAll('.palette-choice').forEach(other=>other.setAttribute('aria-pressed',String(other===button)));demo.querySelector('.palette-label').textContent=button.dataset.label})})});
document.querySelectorAll('.ba-slider').forEach(slider=>{const range=slider.querySelector('.ba-range');if(!range)return;const update=()=>slider.style.setProperty('--pos',range.value+'%');range.addEventListener('input',update);update()});
